name: loong
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - boost=1.74.0=py310h7c3ba0c_5
  - boost-cpp=1.74.0=h75c5d50_8
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - fontconfig=2.14.1=hef1e5e3_0
  - freetype=2.10.4=hca18f0e_2
  - gettext=0.21.1=h27087fc_0
  - glib=2.78.4=hfc55251_0
  - glib-tools=2.78.4=hfc55251_0
  - greenlet=3.0.3=py310hc6cd4ac_0
  - icu=70.1=h27087fc_0
  - jpeg=9e=h0b41bf4_3
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=21_linux64_openblas
  - libcblas=3.9.0=21_linux64_openblas
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.4=h783c2da_0
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=21_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libpng=1.6.42=h2797004_0
  - libsqlite=3.45.1=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.16=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.9.14=h22db469_4
  - libzlib=1.2.13=hd590300_5
  - matplotlib-base=3.4.3=py310h23f4a51_2
  - ncurses=6.4=h59595ed_2
  - numpy=1.26.4=py310hb13e2d6_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.2.1=hd590300_0
  - pandas=2.2.0=py310hcc13569_0
  - pcre2=10.42=hcad00b1_0
  - pillow=10.2.0=py310h5eee18b_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycairo=1.23.0=py310hd1222b9_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - python=3.10.13=hd12c33a_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - rdkit=2022.03.5=py310h1c297d8_0
  - readline=8.2=h8228510_1
  - reportlab=3.6.13=py310h5eee18b_0
  - setuptools=69.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=2.0.27=py310h2372a71_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.3.3=py310h2372a71_1
  - typing-extensions=4.9.0=hd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - astor==0.8.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - charset-normalizer==3.3.2
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - contextlib2==21.6.0
      - echo_logger==0.1.4
      - filelock==3.11.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - grpcio==1.60.1
      - idna==3.6
      - jinja2==3.1.3
      - joblib==1.3.2
      - json-tricks==3.17.3
      - lightning-utilities==0.10.1
      - markdown==3.5.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.2.1
      - nni==3.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.535.133
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - packaging==23.2
      - prettytable==3.9.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - pythonwebhdfs==0.2.3
      - pytorch-lightning==2.2.0.post0
      - pyyaml==6.0.1
      - requests==2.31.0
      - responses==0.25.0
      - schema==0.7.5
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - simplejson==3.19.2
      - sympy==1.12
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.3.0
      - torch==2.1.0
      - torch-geometric==2.5.0
      - torchmetrics==1.2.1
      - tqdm==4.66.2
      - triton==2.1.0
      - typeguard==4.1.2
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - websockets==12.0
      - werkzeug==3.0.1
      - yarl==1.9.4
