name: scage-1
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libsqlite=3.45.2
  - libuuid=1.41.5
  - libzlib=1.2.13
  - ncurses=6.4.20240210
  - openssl=3.2.1
  - pip=24.0
  - python=3.10.13
  - readline=8.2
  - setuptools=69.2.0
  - sqlite=3.45.2
  - tk=8.6.13
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  